### ISSUE TITLE
Matrix room not joinable due to misconfigured SRV record

### ISSUE THREAD

**Issue by MTRNord** [LemmyNet/activitypub-federation-rust#16]
Sorry for doing this issue in here as I have no other way to reach you :)

It seems like synapse fails to fetch the alias, and it's probably due to the error mentioned in https://federationtester.matrix.org/#asonix.dog Any chance this could be fixed, or another alias be added? :)

**Comment by Nutomic** [comment]
Not sure what the problem might be. This is the room address as shown in Element: `#activitystreams:matrix.asonix.dog`

**Comment by MTRNord** [comment]
> Not sure what the problem might be. This is the room address as shown in Element: `#activitystreams:matrix.asonix.dog`

Well my Synapse tells me that the room alias cannot be fetched so I assume that maybe it cannot communicate as it doesn't like the cname on that domain. 😬 Could you maybe try to invite @mtrnord:midnightthoughts.space instead? Maybe it's some other issue. Synapse sadly doesn't log any error on why it wasn't able to fetch the alias :/
