### ISSUE TITLE
Support secure-mode federation

### ISSUE THREAD

**Issue by darrinsmart** [LemmyNet/activitypub-federation-rust#35]
Some fediverse software runs in "secure mode", requiring HTTP signatures for most endpoints.

Mastodon has it as an option: https://docs.joinmastodon.org/admin/config/#authorized_fetch

In GoToSocial it is mandatory: https://github.com/superseriousbusiness/gotosocial#safety--security-features

I took the live_federation example and added some code to dereference an account on my GoToSocial instance:
```
let user_id = ObjectId::<DbUser>::parse("https://gts.djs.to/@darrin")?;
let data = config.to_request_data();
let user = user_id.dereference(&data).await?;
```
This fails with the log:
```
[INFO  activitypub_federation::fetch] Fetching remote object https://gts.djs.to/@darrin
[WARN  background_jobs_actix] Dropping manager, tearing down workers
[WARN  background_jobs_actix] Stopping and joining arbiter
[WARN  background_jobs_actix] Stopping and joining arbiter
[WARN  background_jobs_actix::worker] Not restarting worker, Arbiter is dead
[WARN  background_jobs_actix::worker] Not restarting worker, Arbiter is dead
.. repeated many times ..
Error: Error(Other errors which are not explicitly handled)
```

My server logs `http request wasn't signed or http signature was invalid`.

I think this will involve an API change, as the private key of the requesting actor is required to sign the request.

**Comment by Nutomic** [comment]
Feel free to contribute such a feature. You will have to to create such a signature in [fetch_object_http()](https://github.com/LemmyNet/activitypub-federation-rust/blob/main/src/fetch/mod.rs#L29). For that you need something similar to [sign_request()](https://github.com/LemmyNet/activitypub-federation-rust/blob/main/src/http_signatures.rs#L59), which is used for signing inbox POST requests.

**Comment by Alexis211** [comment]
I'm also interested in this, I will probably try to make a prototype and open a PR soon

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/activitypub-federation-rust/pull/39
