### ISSUE TITLE
Error when trying to use ObjectId::parse

### ISSUE THREAD

**Issue by maksalees** [LemmyNet/activitypub-federation-rust#70]
When I try to `ObjectId::<ApUser>::parse(user.ap_id.into())`, I get this

```
ObjectId::<ApUser>::parse(user.ap_id.into())
   |                 -------------------------------- ^^^^^^^^^^^^^^^ the trait `From<Infallible>` is not implemented for `url::ParseError`
   |                 |
   |                 required by a bound introduced by this call
```

`user.ap_id` have String type and contains ActivityPub ID of object.

**Comment by Nutomic** [comment]
Looks like a problem with handling the error. It should compile if you put `unwrap()` at the end.

**Comment by Nutomic** [comment]
Fixed by https://github.com/LemmyNet/activitypub-federation-rust/pull/84
