### ISSUE TITLE
Upgrade `hyper` and `http` dependencies to 1.0

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/activitypub-federation-rust#87]
These result in a lot of breaking changes which arent easy to resolve.

https://github.com/hyperium/hyper/blob/master/CHANGELOG.md#v100-2023-11-15

https://github.com/hyperium/http/blob/master/CHANGELOG.md#100-november-15-2023

**Comment by j0lol** [comment]
Depends on https://github.com/actix/actix-web/pull/3208, cant update http until actix does

**Comment by j0lol** [comment]
Also reqwest has not updated to http 1.0: https://github.com/seanmonstar/reqwest/pull/2059

**Comment by j0lol** [comment]
Here's my best attempt at getting it working on hyper/http 1: https://github.com/j0lol/activitypub-federation-rust

I had to remove actix (for now) and tests fail because of reqwest but it seems to work on my project? I have not tested it much though

**Comment by kwaa** [comment]
It looks like `actix-web` won't upgrade `http` crate until v5, and v5 has no due date...
